### ISSUE TITLE
Add daemon Support

### ISSUE THREAD

**Issue by ghost** [niansa/simpsh-httpd#5]
Please add a Daemon Support, so the webserver could be launched in the background, without having it constantly open :)

**Comment by ghost** [comment]
Workaround solution:

Create startup script which detects if tmux or screen is installed, and launch it with them in background :)

**Comment by niansa** [comment]
Ok, i just created a init service, now i'm working at daemon support.

**Comment by niansa** [comment]
I removed init service again and added daemon mode. (Parameter: -d or --daemon)
